// Obtiene la transcripción (subtítulos) pública de un vídeo de YouTube.
//
// YouTube no expone esto como una API oficial ni permite leerlo con CORS
// directo desde un dominio ajeno, así que:
//   1. Intentamos leer la página del vídeo directamente.
//   2. Si el navegador bloquea la petición por CORS, reintentamos a través
//      de un proxy CORS configurable (ver ajustes ⚙️).
// Si el vídeo no tiene ningún subtítulo (ni siquiera autogenerado), no hay
// forma de transcribirlo sin descargar y procesar el audio en un backend
// (p. ej. con Whisper) — eso queda fuera de este front-end estático y se
// documenta como mejora futura en el README.

function decodeHtmlEntities(str) {
  const el = document.createElement("textarea");
  el.innerHTML = str;
  return el.value;
}

async function fetchText(url, corsProxy) {
  try {
    const res = await fetch(url);
    if (res.ok) return await res.text();
  } catch {
    /* probablemente CORS: seguimos con el proxy */
  }
  const proxied = corsProxy + encodeURIComponent(url);
  const res = await fetch(proxied);
  if (!res.ok) throw new Error(`No se pudo obtener ${url} (status ${res.status})`);
  return res.text();
}

function extractJsonArrayAfter(html, marker) {
  const idx = html.indexOf(marker);
  if (idx === -1) return null;
  const start = idx + marker.length;
  if (html[start] !== "[") return null;
  let depth = 0;
  let i = start;
  for (; i < html.length; i++) {
    const ch = html[i];
    if (ch === "[") depth++;
    else if (ch === "]") {
      depth--;
      if (depth === 0) {
        i++;
        break;
      }
    }
  }
  try {
    return JSON.parse(html.slice(start, i));
  } catch {
    return null;
  }
}

function pickBestTrack(tracks, preferredLang) {
  if (!tracks?.length) return null;
  const byLang = (lang) =>
    tracks.find((t) => t.languageCode?.toLowerCase().startsWith(lang));

  const manual = tracks.filter((t) => t.kind !== "asr");
  return (
    (preferredLang && byLang(preferredLang.slice(0, 2))) ||
    manual.find((t) => t.languageCode?.startsWith("es")) ||
    manual.find((t) => t.languageCode?.startsWith("en")) ||
    manual[0] ||
    tracks.find((t) => t.languageCode?.startsWith("es")) ||
    tracks.find((t) => t.languageCode?.startsWith("en")) ||
    tracks[0]
  );
}

function parseTimedTextXml(xmlText) {
  const doc = new DOMParser().parseFromString(xmlText, "text/xml");
  const nodes = Array.from(doc.getElementsByTagName("text"));
  return nodes
    .map((node) => ({
      start: parseFloat(node.getAttribute("start") || "0"),
      duration: parseFloat(node.getAttribute("dur") || "0"),
      text: decodeHtmlEntities(node.textContent || "").replace(/\s+/g, " ").trim(),
    }))
    .filter((c) => c.text);
}

/**
 * @returns {Promise<{cues: {start:number, duration:number, text:string}[], languageCode: string, isAutoGenerated: boolean} | null>}
 *   null si el vídeo no tiene ningún subtítulo disponible.
 */
export async function fetchTranscript(videoId, corsProxy) {
  const watchUrl = `https://www.youtube.com/watch?v=${videoId}&hl=en`;
  const html = await fetchText(watchUrl, corsProxy);

  const tracks = extractJsonArrayAfter(html, '"captionTracks":');
  if (!tracks || tracks.length === 0) return null;

  const track = pickBestTrack(tracks, navigator.language);
  if (!track?.baseUrl) return null;

  // baseUrl viene como URL absoluta a www.youtube.com/api/timedtext
  const xml = await fetchText(track.baseUrl, corsProxy);
  const cues = parseTimedTextXml(xml);
  if (cues.length === 0) return null;

  return {
    cues,
    languageCode: track.languageCode || "?",
    isAutoGenerated: track.kind === "asr",
  };
}

export function cuesToTimestampedText(cues, { maxChars = 18000 } = {}) {
  const lines = [];
  let total = 0;
  for (const cue of cues) {
    const mm = Math.floor(cue.start / 60);
    const ss = String(Math.floor(cue.start % 60)).padStart(2, "0");
    const line = `[${mm}:${ss}] ${cue.text}`;
    total += line.length + 1;
    if (total > maxChars) break;
    lines.push(line);
  }
  return lines.join("\n");
}
